// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/db/db.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/db/db.go -destination=internal/mock_storage/mock.go
//

// Package mock_db is a generated GoMock package.
package mock_db
